# Generated by Django 5.0 on 2023-12-09 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('receive_email_login', models.EmailField(blank=True, max_length=254, null=True)),
                ('receive_email_password', models.CharField(blank=True, max_length=254, null=True)),
                ('receive_email_receiver', models.EmailField(blank=True, max_length=254, null=True)),
                ('mail_server', models.CharField(blank=True, max_length=254, null=True)),
                ('mail_port', models.IntegerField(blank=True, null=True)),
                ('mail_SSL', models.BooleanField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JumpSessionModel',
            fields=[
                ('start_datetime', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('count', models.IntegerField()),
                ('average_high', models.FloatField()),
                ('highest', models.FloatField()),
                ('plotly_html', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JumpSessionJumpsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('jump_height', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotmyvert_backend_api.jumpsessionmodel')),
            ],
        ),
    ]
