# Generated by Django 5.0 on 2023-12-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotmyvert_backend_api', '0002_jumpsessionmodel_plotly_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumpsessionmodel',
            name='plotly_html',
        ),
    ]
